### ISSUE TITLE
Changing how ghci is started

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/atom-tidalcycles#77]
The `ghci path` setting is also used by people to change the ghci parameters, e.g. switching to stack using instructions at the end of this page:
  https://tidalcycles.org/index.php/Troubleshooting_a_Tidal_install#Installing_via_.27stack.27_rather_than_.27cabal.27

It seems this isn't working at the moment:
  https://forum.toplap.org/t/trouble-setting-up-tidal-stack-install/902

Sorry this is my fault, I'd forgotten about this!

So I suppose we do need an extra configuration parameter, one for the path to Haskell, and one for the command to run to start ghci.

**Comment by ndr-brt** [comment]
This kind of ghci path:
`stack exec --package tidal -- ghci`
Is already handled (v.3.7.3), an user wrote me a line about that bug.

But

**Comment by ndr-brt** [comment]
I'm not too familiar with the haskell environment so...
Ghci path, as defined in the plug-in, is not the ghci path, but is the ghci command. It does not necessarily represent a path but it can represent an instruction to run ghci. At the moment it works with no problems.
At the moment the issue is that, in the case of a "stack type of ghci path", is impossible for the plugin to find the tidal installation BootFile because it replace "ghci" with "ghc-pkg" and it doesn't work. 
Fortunately there's the good old plugin BootFile fallback :)

Yes, we can introduce another property for the haskell installation, would be easy because I already separated class GHCI from GHC (that could be called Haskell)
